# CMake generated Testfile for 
# Source directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/Partition
# Build directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/Partition
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PartitionTest1_1 "PartitionTests" "test1" "./TestData/test1.bin" "./TestData/comm1.txt" "6" "3" "9")
set_tests_properties(PartitionTest1_1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  2 }{ 0  1  2 }{ 0 }" TIMEOUT "1")
add_test(PartitionTest1_2 "PartitionTests" "test1" "./TestData/test2.bin" "./TestData/comm2.txt" "7" "5" "3")
set_tests_properties(PartitionTest1_2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1 }{ 2 }{ 1  2 }" TIMEOUT "1")
add_test(PartitionTest1_3 "PartitionTests" "test1" "./TestData/test3.bin" "./TestData/comm3.txt" "0" "29" "15")
set_tests_properties(PartitionTest1_3 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  4 }{ 0  4 }{ 3 }" TIMEOUT "1")
add_test(PartitionTest1_4 "PartitionTests" "test1" "./TestData/test4.bin" "./TestData/comm4.txt" "0" "8" "10")
set_tests_properties(PartitionTest1_4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  2  3 }{ 0  1 }{ 1  2  3 }" TIMEOUT "1")
add_test(PartitionTest1_5 "PartitionTests" "test1" "./TestData/test5.bin" "./TestData/comm5.txt" "5" "4" "11")
set_tests_properties(PartitionTest1_5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  2  3 }{ 0  1  2 }{ 0  2  3 }" TIMEOUT "1")
add_test(PartitionTest2_1 "PartitionTests" "test2" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(PartitionTest2_1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2 }" TIMEOUT "1")
add_test(PartitionTest2_2 "PartitionTests" "test2" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(PartitionTest2_2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2 }" TIMEOUT "1")
add_test(PartitionTest2_3 "PartitionTests" "test2" "./TestData/test3.bin" "./TestData/comm3.txt")
set_tests_properties(PartitionTest2_3 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  4 }" TIMEOUT "1")
add_test(PartitionTest2_4 "PartitionTests" "test2" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(PartitionTest2_4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3 }" TIMEOUT "1")
add_test(PartitionTest2_5 "PartitionTests" "test2" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(PartitionTest2_5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3 }" TIMEOUT "1")
add_test(PartitionTest3_1 "PartitionTests" "test3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(PartitionTest3_1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest3_2 "PartitionTests" "test3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test1.bin" "./TestData/notcomm1.txt")
set_tests_properties(PartitionTest3_2 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal" TIMEOUT "1")
add_test(PartitionTest3_3 "PartitionTests" "test3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(PartitionTest3_3 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal" TIMEOUT "1")
add_test(PartitionTest4_1 "PartitionTests" "test4" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(PartitionTest4_1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest4_2 "PartitionTests" "test4" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(PartitionTest4_2 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest4_3 "PartitionTests" "test4" "./TestData/test3.bin" "./TestData/comm3.txt")
set_tests_properties(PartitionTest4_3 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest4_4 "PartitionTests" "test4" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(PartitionTest4_4 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest4_5 "PartitionTests" "test4" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(PartitionTest4_5 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_1 "PartitionTests" "test5" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/agrtest1.bin")
set_tests_properties(PartitionTest5_1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_2 "PartitionTests" "test5" "./TestData/test2.bin" "./TestData/comm2.txt" "./TestData/agrtest2.bin")
set_tests_properties(PartitionTest5_2 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_3 "PartitionTests" "test5" "./TestData/test3.bin" "./TestData/comm3.txt" "./TestData/agrtest3.bin")
set_tests_properties(PartitionTest5_3 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_4 "PartitionTests" "test5" "./TestData/test4.bin" "./TestData/comm4.txt" "./TestData/agrtest4.bin")
set_tests_properties(PartitionTest5_4 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_5 "PartitionTests" "test5" "./TestData/test5.bin" "./TestData/comm5.txt" "./TestData/agrtest5.bin")
set_tests_properties(PartitionTest5_5 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal" TIMEOUT "1")
add_test(PartitionTest5_6 "PartitionTests" "test5" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/notagrtest1.bin")
set_tests_properties(PartitionTest5_6 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal" TIMEOUT "1")
add_test(PartitionTest6_1 "PartitionTests" "test6" "./TestData/test1.bin" "./TestData/comm1.txt" "1" "0" "2")
set_tests_properties(PartitionTest6_1 PROPERTIES  PASS_REGULAR_EXPRESSION "5 2 3" TIMEOUT "1")
add_test(PartitionTest6_2 "PartitionTests" "test6" "./TestData/test2.bin" "./TestData/comm2.txt" "0" "1" "2")
set_tests_properties(PartitionTest6_2 PROPERTIES  PASS_REGULAR_EXPRESSION "3 4 3" TIMEOUT "1")
add_test(PartitionTest6_3 "PartitionTests" "test6" "./TestData/test3.bin" "./TestData/comm3.txt" "4" "3" "0")
set_tests_properties(PartitionTest6_3 PROPERTIES  PASS_REGULAR_EXPRESSION "4 7 8" TIMEOUT "1")
add_test(PartitionTest6_4 "PartitionTests" "test6" "./TestData/test4.bin" "./TestData/comm4.txt" "0" "3" "1")
set_tests_properties(PartitionTest6_4 PROPERTIES  PASS_REGULAR_EXPRESSION "9 6 5" TIMEOUT "1")
add_test(PartitionTest6_5 "PartitionTests" "test6" "./TestData/test5.bin" "./TestData/comm5.txt" "0" "2" "3")
set_tests_properties(PartitionTest6_5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 5 2" TIMEOUT "1")
add_test(PartitionTest7_1 "PartitionTests" "test7" "./TestData/test1.bin" "./TestData/comm1.txt" "1" "0" "2")
set_tests_properties(PartitionTest7_1 PROPERTIES  PASS_REGULAR_EXPRESSION "5 2 3" TIMEOUT "1")
add_test(PartitionTest7_2 "PartitionTests" "test7" "./TestData/test2.bin" "./TestData/comm2.txt" "0" "1" "2")
set_tests_properties(PartitionTest7_2 PROPERTIES  PASS_REGULAR_EXPRESSION "3 4 3" TIMEOUT "1")
add_test(PartitionTest7_3 "PartitionTests" "test7" "./TestData/test3.bin" "./TestData/comm3.txt" "4" "3" "0")
set_tests_properties(PartitionTest7_3 PROPERTIES  PASS_REGULAR_EXPRESSION "4 7 8" TIMEOUT "1")
add_test(PartitionTest7_4 "PartitionTests" "test7" "./TestData/test4.bin" "./TestData/comm4.txt" "0" "3" "1")
set_tests_properties(PartitionTest7_4 PROPERTIES  PASS_REGULAR_EXPRESSION "9 6 5" TIMEOUT "1")
add_test(PartitionTest7_5 "PartitionTests" "test7" "./TestData/test5.bin" "./TestData/comm5.txt" "0" "2" "3")
set_tests_properties(PartitionTest7_5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 5 2" TIMEOUT "1")
