# CMake generated Testfile for 
# Source directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/Partition
# Build directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/Partition
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(P1Test1 "PartitionTest1" "./TestData/test1.bin" "./TestData/comm1.txt" "6" "3" "9")
set_tests_properties(P1Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  2 }{ 0  1  2 }{ 0 }")
add_test(P1Test2 "PartitionTest1" "./TestData/test2.bin" "./TestData/comm2.txt" "7" "5" "3")
set_tests_properties(P1Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1 }{ 2 }{ 1  2 }")
add_test(P1Test3 "PartitionTest1" "./TestData/test3.bin" "./TestData/comm3.txt" "0" "29" "15")
set_tests_properties(P1Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  4 }{ 0  4 }{ 3 }")
add_test(P1Test4 "PartitionTest1" "./TestData/test4.bin" "./TestData/comm4.txt" "0" "8" "10")
set_tests_properties(P1Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  2  3 }{ 0  1 }{ 1  2  3 }")
add_test(P1Test5 "PartitionTest1" "./TestData/test5.bin" "./TestData/comm5.txt" "5" "4" "11")
set_tests_properties(P1Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  2  3 }{ 0  1  2 }{ 0  2  3 }")
add_test(P2Test1 "PartitionTest2" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(P2Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2 }")
add_test(P2Test2 "PartitionTest2" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(P2Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2 }")
add_test(P2Test3 "PartitionTest2" "./TestData/test3.bin" "./TestData/comm3.txt")
set_tests_properties(P2Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  4 }")
add_test(P2Test4 "PartitionTest2" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(P2Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3 }")
add_test(P2Test5 "PartitionTest2" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(P2Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3 }")
add_test(P3Test1 "PartitionTest3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(P3Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P3Test2 "PartitionTest3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test1.bin" "./TestData/notcomm1.txt")
set_tests_properties(P3Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal")
add_test(P3Test3 "PartitionTest3" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(P3Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal")
add_test(P4Test1 "PartitionTest4" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(P4Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P4Test2 "PartitionTest4" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(P4Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P4Test3 "PartitionTest4" "./TestData/test3.bin" "./TestData/comm3.txt")
set_tests_properties(P4Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P4Test4 "PartitionTest4" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(P4Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P4Test5 "PartitionTest4" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(P4Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test1 "PartitionTest5" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/agrtest1.bin")
set_tests_properties(P5Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test2 "PartitionTest5" "./TestData/test2.bin" "./TestData/comm2.txt" "./TestData/agrtest2.bin")
set_tests_properties(P5Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test3 "PartitionTest5" "./TestData/test3.bin" "./TestData/comm3.txt" "./TestData/agrtest3.bin")
set_tests_properties(P5Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test4 "PartitionTest5" "./TestData/test4.bin" "./TestData/comm4.txt" "./TestData/agrtest4.bin")
set_tests_properties(P5Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test5 "PartitionTest5" "./TestData/test5.bin" "./TestData/comm5.txt" "./TestData/agrtest5.bin")
set_tests_properties(P5Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "Equal")
add_test(P5Test6 "PartitionTest5" "./TestData/test1.bin" "./TestData/comm1.txt" "./TestData/notagrtest1.bin")
set_tests_properties(P5Test6 PROPERTIES  PASS_REGULAR_EXPRESSION "Not Equal")
add_test(P6Test1 "PartitionTest6" "./TestData/test1.bin" "./TestData/comm1.txt" "1" "0" "2")
set_tests_properties(P6Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "5 2 3" TIMEOUT "1")
add_test(P6Test2 "PartitionTest6" "./TestData/test2.bin" "./TestData/comm2.txt" "0" "1" "2")
set_tests_properties(P6Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "3 4 3" TIMEOUT "1")
add_test(P6Test3 "PartitionTest6" "./TestData/test3.bin" "./TestData/comm3.txt" "4" "3" "0")
set_tests_properties(P6Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "4 7 8" TIMEOUT "1")
add_test(P6Test4 "PartitionTest6" "./TestData/test4.bin" "./TestData/comm4.txt" "0" "3" "1")
set_tests_properties(P6Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "9 6 5" TIMEOUT "1")
add_test(P6Test5 "PartitionTest6" "./TestData/test5.bin" "./TestData/comm5.txt" "0" "2" "3")
set_tests_properties(P6Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 5 2" TIMEOUT "1")
