# CMake generated Testfile for 
# Source directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/GraphClustering/Leiden
# Build directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/GraphClustering/Leiden
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(LeidTest1_1 "LeidenTests" "test1" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(LeidTest1_1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  2  3  5  6 }" TIMEOUT "1")
add_test(LeidTest1_2 "LeidenTests" "test1" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(LeidTest1_2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  7 }" TIMEOUT "1")
add_test(LeidTest1_3 "LeidenTests" "test1" "./TestData/test3.bin" "./TestData/comm3.txt")
set_tests_properties(LeidTest1_3 PROPERTIES  TIMEOUT "1")
add_test(LeidTest1_4 "LeidenTests" "test1" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(LeidTest1_4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  8  10  13  14  15  16  21 }" TIMEOUT "1")
add_test(LeidTest1_5 "LeidenTests" "test1" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(LeidTest1_5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  4  5  6  8  11 }" TIMEOUT "1")
add_test(LeidTest2_1 "LeidenTests" "test2" "./TestData/test1.bin" "./TestData/comm1.txt" "0" "1" "2" "4" "8")
set_tests_properties(LeidTest2_1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0 }" TIMEOUT "1")
add_test(LeidTest2_2 "LeidenTests" "test2" "./TestData/test2.bin" "./TestData/comm2.txt" "0" "3" "8" "9")
set_tests_properties(LeidTest2_2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 8 }" TIMEOUT "1")
add_test(LeidTest2_3 "LeidenTests" "test2" "./TestData/test3.bin" "./TestData/comm3.txt" "0" "3" "4" "5")
set_tests_properties(LeidTest2_3 PROPERTIES  PASS_REGULAR_EXPRESSION "{}" TIMEOUT "1")
add_test(LeidTest2_4 "LeidenTests" "test2" "./TestData/test4.bin" "./TestData/comm4.txt" "15" "21" "22" "23")
set_tests_properties(LeidTest2_4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 21 }" TIMEOUT "1")
add_test(LeidTest2_5 "LeidenTests" "test2" "./TestData/test5.bin" "./TestData/comm5.txt" "2" "3" "4" "6" "7")
set_tests_properties(LeidTest2_5 PROPERTIES  PASS_REGULAR_EXPRESSION "{}" TIMEOUT "1")
add_test(LeidTest3_1 "LeidenTests" "test3" "./TestData/test1.bin" "./TestData/ChRandCommTest1.txt" "0" "1" "3" "4" "4")
set_tests_properties(LeidTest3_1 PROPERTIES  FAIL_REGULAR_EXPRESSION "F" PASS_REGULAR_EXPRESSION "P" TIMEOUT "1")
add_test(LeidTest3_2 "LeidenTests" "test3" "./TestData/test2.bin" "./TestData/SinglComm2.txt" "1" "4" "8")
set_tests_properties(LeidTest3_2 PROPERTIES  FAIL_REGULAR_EXPRESSION "F" PASS_REGULAR_EXPRESSION "P" TIMEOUT "1")
add_test(LeidTest3_3 "LeidenTests" "test3" "./TestData/test3.bin" "./TestData/SinglComm3.txt" "2" "4" "6" "9" "8" "13" "0")
set_tests_properties(LeidTest3_3 PROPERTIES  FAIL_REGULAR_EXPRESSION "F" PASS_REGULAR_EXPRESSION "P" TIMEOUT "1")
add_test(LeidTest3_4 "LeidenTests" "test3" "./TestData/test4.bin" "./TestData/SinglComm4.txt" "2" "6" "0")
set_tests_properties(LeidTest3_4 PROPERTIES  FAIL_REGULAR_EXPRESSION "F" PASS_REGULAR_EXPRESSION "P" TIMEOUT "1")
add_test(LeidTest3_5 "LeidenTests" "test3" "./TestData/test5.bin" "./TestData/SinglComm5.txt" "3" "6" "3")
set_tests_properties(LeidTest3_5 PROPERTIES  FAIL_REGULAR_EXPRESSION "F" PASS_REGULAR_EXPRESSION "P" TIMEOUT "1")
add_test(LeidTest4_1 "LeidenTests" "test4" "./TestData/test1.bin" "./TestData/SinglComm1.txt" "7" "1" "3")
set_tests_properties(LeidTest4_1 PROPERTIES  PASS_REGULAR_EXPRESSION " 0  1  0 " TIMEOUT "1")
add_test(LeidTest4_2 "LeidenTests" "test4" "./TestData/test2.bin" "./TestData/SinglComm2.txt" "8" "2" "4")
set_tests_properties(LeidTest4_2 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(LeidTest4_3 "LeidenTests" "test4" "./TestData/test3.bin" "./TestData/SinglComm3.txt" "29" "24" "9")
set_tests_properties(LeidTest4_3 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(LeidTest4_4 "LeidenTests" "test4" "./TestData/test4.bin" "./TestData/SinglComm4.txt" "20" "1" "11")
set_tests_properties(LeidTest4_4 PROPERTIES  PASS_REGULAR_EXPRESSION " 0  0  0 " TIMEOUT "1")
add_test(LeidTest4_5 "LeidenTests" "test4" "./TestData/test5.bin" "./TestData/SinglComm5.txt" "9" "5" "2")
set_tests_properties(LeidTest4_5 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(LeidTest5_1 "LeidenTests" "test5" "./TestData/test1.bin" "./TestData/SinglComm1.txt")
set_tests_properties(LeidTest5_1 PROPERTIES  TIMEOUT "1")
add_test(LeidTest5_2 "LeidenTests" "test5" "./TestData/test2.bin" "./TestData/SinglComm2.txt")
set_tests_properties(LeidTest5_2 PROPERTIES  TIMEOUT "1")
add_test(LeidTest5_3 "LeidenTests" "test5" "./TestData/test3.bin" "./TestData/SinglComm3.txt")
set_tests_properties(LeidTest5_3 PROPERTIES  TIMEOUT "1")
add_test(LeidTest5_4 "LeidenTests" "test5" "./TestData/test4.bin" "./TestData/SinglComm4.txt")
set_tests_properties(LeidTest5_4 PROPERTIES  TIMEOUT "1")
add_test(LeidTest5_5 "LeidenTests" "test5" "./TestData/test5.bin" "./TestData/SinglComm5.txt")
set_tests_properties(LeidTest5_5 PROPERTIES  TIMEOUT "1")
add_test(LeidTest6_1 "LeidenTests" "test6" "./TestData/test1.bin" "./TestData/SinglComm1.txt")
set_tests_properties(LeidTest6_1 PROPERTIES  TIMEOUT "1")
add_test(LeidTest6_2 "LeidenTests" "test6" "./TestData/test2.bin" "./TestData/SinglComm2.txt")
set_tests_properties(LeidTest6_2 PROPERTIES  TIMEOUT "1")
add_test(LeidTest6_3 "LeidenTests" "test6" "./TestData/test3.bin" "./TestData/SinglComm3.txt")
set_tests_properties(LeidTest6_3 PROPERTIES  TIMEOUT "1")
add_test(LeidTest6_4 "LeidenTests" "test6" "./TestData/test4.bin" "./TestData/SinglComm4.txt")
set_tests_properties(LeidTest6_4 PROPERTIES  TIMEOUT "1")
add_test(LeidTest6_5 "LeidenTests" "test6" "./TestData/test5.bin" "./TestData/SinglComm5.txt")
set_tests_properties(LeidTest6_5 PROPERTIES  TIMEOUT "1")
add_test(LeidTest7_1 "LeidenTests" "test7" "./TestData/test1.bin" "./TestData/SinglComm1.txt")
set_tests_properties(LeidTest7_1 PROPERTIES  TIMEOUT "1")
add_test(LeidTest7_2 "LeidenTests" "test7" "./TestData/test2.bin" "./TestData/SinglComm2.txt")
set_tests_properties(LeidTest7_2 PROPERTIES  TIMEOUT "1")
add_test(LeidTest7_3 "LeidenTests" "test7" "./TestData/test3.bin" "./TestData/SinglComm3.txt")
set_tests_properties(LeidTest7_3 PROPERTIES  TIMEOUT "1")
add_test(LeidTest7_4 "LeidenTests" "test7" "./TestData/test4.bin" "./TestData/SinglComm4.txt")
set_tests_properties(LeidTest7_4 PROPERTIES  TIMEOUT "1")
add_test(LeidTest7_5 "LeidenTests" "test7" "./TestData/test5.bin" "./TestData/SinglComm5.txt")
set_tests_properties(LeidTest7_5 PROPERTIES  TIMEOUT "1")
add_test(LeidTest9_1 "LeidenTests" "test9" "./TestData/test1.bin")
set_tests_properties(LeidTest9_1 PROPERTIES  TIMEOUT "2")
add_test(LeidTest9_2 "LeidenTests" "test9" "./TestData/test2.bin")
set_tests_properties(LeidTest9_2 PROPERTIES  TIMEOUT "2")
add_test(LeidTest9_3 "LeidenTests" "test9" "./TestData/test3.bin")
set_tests_properties(LeidTest9_3 PROPERTIES  TIMEOUT "2")
add_test(LeidTest9_4 "LeidenTests" "test9" "./TestData/test4.bin")
set_tests_properties(LeidTest9_4 PROPERTIES  TIMEOUT "2")
add_test(LeidTest9_5 "LeidenTests" "test9" "./TestData/test5.bin")
set_tests_properties(LeidTest9_5 PROPERTIES  TIMEOUT "2")
