# CMake generated Testfile for 
# Source directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/GraphClustering/Leiden
# Build directory: /run/media/konstantin/NameD/Home/git/GraphClusteringLib/test/GraphClustering/Leiden
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Leid1Test1 "LeidenTest1" "./TestData/test1.bin" "./TestData/comm1.txt")
set_tests_properties(Leid1Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  2  3  5  6 }" TIMEOUT "1")
add_test(Leid1Test2 "LeidenTest1" "./TestData/test2.bin" "./TestData/comm2.txt")
set_tests_properties(Leid1Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  2  3  7 }" TIMEOUT "1")
add_test(Leid1Test4 "LeidenTest1" "./TestData/test4.bin" "./TestData/comm4.txt")
set_tests_properties(Leid1Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0  1  8  10  13  14  15  16  21 }" TIMEOUT "1")
add_test(Leid1Test5 "LeidenTest1" "./TestData/test5.bin" "./TestData/comm5.txt")
set_tests_properties(Leid1Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 1  4  5  6  8  11 }" TIMEOUT "1")
add_test(Leid2Test1 "LeidenTest2" "./TestData/test1.bin" "./TestData/comm1.txt" "0" "1" "2" "4" "8")
set_tests_properties(Leid2Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 0 }" TIMEOUT "1")
add_test(Leid2Test2 "LeidenTest2" "./TestData/test2.bin" "./TestData/comm2.txt" "0" "3" "8" "9")
set_tests_properties(Leid2Test2 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 8 }" TIMEOUT "1")
add_test(Leid2Test3 "LeidenTest2" "./TestData/test3.bin" "./TestData/comm3.txt" "0" "3" "4" "5")
set_tests_properties(Leid2Test3 PROPERTIES  PASS_REGULAR_EXPRESSION "{}" TIMEOUT "1")
add_test(Leid2Test4 "LeidenTest2" "./TestData/test4.bin" "./TestData/comm4.txt" "15" "21" "22" "23")
set_tests_properties(Leid2Test4 PROPERTIES  PASS_REGULAR_EXPRESSION "{ 21 }" TIMEOUT "1")
add_test(Leid2Test5 "LeidenTest2" "./TestData/test5.bin" "./TestData/comm5.txt" "2" "3" "4" "6" "7")
set_tests_properties(Leid2Test5 PROPERTIES  PASS_REGULAR_EXPRESSION "{}" TIMEOUT "1")
add_test(Leid3Test1 "LeidenTest3" "./TestData/test1.bin" "./TestData/ChRandCommTest1.txt" "0" "1" "3" "4" "4")
set_tests_properties(Leid3Test1 PROPERTIES  PASS_REGULAR_EXPRESSION "" TIMEOUT "1")
add_test(Leid3Test2 "LeidenTest3" "./TestData/test2.bin" "./TestData/SinglComm2.txt" "1" "4" "8")
set_tests_properties(Leid3Test2 PROPERTIES  TIMEOUT "1")
add_test(Leid3Test3 "LeidenTest3" "./TestData/test3.bin" "./TestData/SinglComm3.txt" "2" "4" "6" "9" "8" "13" "0")
set_tests_properties(Leid3Test3 PROPERTIES  TIMEOUT "1")
add_test(Leid3Test4 "LeidenTest3" "./TestData/test4.bin" "./TestData/SinglComm4.txt" "2" "6" "0")
set_tests_properties(Leid3Test4 PROPERTIES  TIMEOUT "1")
add_test(Leid3Test5 "LeidenTest3" "./TestData/test5.bin" "./TestData/SinglComm5.txt" "3" "6" "3")
set_tests_properties(Leid3Test5 PROPERTIES  TIMEOUT "1")
add_test(Leid4Test1 "LeidenTest4" "./TestData/test1.bin" "./TestData/SinglComm1.txt" "7" "1" "3")
set_tests_properties(Leid4Test1 PROPERTIES  PASS_REGULAR_EXPRESSION " 0  1  0 " TIMEOUT "1")
add_test(Leid4Test2 "LeidenTest4" "./TestData/test2.bin" "./TestData/SinglComm2.txt" "8" "2" "4")
set_tests_properties(Leid4Test2 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(Leid4Test3 "LeidenTest4" "./TestData/test3.bin" "./TestData/SinglComm3.txt" "29" "24" "9")
set_tests_properties(Leid4Test3 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(Leid4Test4 "LeidenTest4" "./TestData/test4.bin" "./TestData/SinglComm4.txt" "20" "1" "11")
set_tests_properties(Leid4Test4 PROPERTIES  PASS_REGULAR_EXPRESSION " 0  0  0 " TIMEOUT "1")
add_test(Leid4Test5 "LeidenTest4" "./TestData/test5.bin" "./TestData/SinglComm5.txt" "9" "5" "2")
set_tests_properties(Leid4Test5 PROPERTIES  PASS_REGULAR_EXPRESSION " 1  0  0 " TIMEOUT "1")
add_test(Leid5Test1 "LeidenTest5" "./TestData/test1.bin" "./TestData/SinglComm1.txt")
set_tests_properties(Leid5Test1 PROPERTIES  TIMEOUT "1")
add_test(Leid5Test2 "LeidenTest5" "./TestData/test2.bin" "./TestData/SinglComm2.txt")
set_tests_properties(Leid5Test2 PROPERTIES  TIMEOUT "1")
add_test(Leid5Test3 "LeidenTest5" "./TestData/test3.bin" "./TestData/SinglComm3.txt")
set_tests_properties(Leid5Test3 PROPERTIES  TIMEOUT "1")
add_test(Leid5Test4 "LeidenTest5" "./TestData/test4.bin" "./TestData/SinglComm4.txt")
set_tests_properties(Leid5Test4 PROPERTIES  TIMEOUT "1")
add_test(Leid5Test5 "LeidenTest5" "./TestData/test5.bin" "./TestData/SinglComm5.txt")
set_tests_properties(Leid5Test5 PROPERTIES  TIMEOUT "1")
